{"data":{"layout-restorer:data":{"main":{"dock":{"type":"tab-area","currentIndex":0,"widgets":["notebook:Lecture1-Conditionals-revised.ipynb"]},"current":"notebook:Lecture9-et-cetera-revised.ipynb"},"down":{"size":0,"widgets":[]},"left":{"collapsed":true,"visible":false,"widgets":["filebrowser","running-sessions","@jupyterlab/toc:plugin","extensionmanager.main-view","jupyter-ai-chat"]},"right":{"collapsed":true,"visible":false,"widgets":["jp-property-inspector","debugger-sidebar"]},"relativeSizes":[0,1,0],"top":{"simpleVisibility":true}},"notebook:Lecture1-Conditionals-revised.ipynb":{"data":{"path":"Lecture1-Conditionals-revised.ipynb","factory":"Notebook"}},"notebook:Lecture0-introduction-0815.ipynb":{"data":{"path":"Lecture0-introduction-0815.ipynb","factory":"Notebook"}},"help-doc:https://docs.python.org/3.8":{"data":{"url":"https://docs.python.org/3.8","text":"Python Reference"}},"notebook:lecture2-Loops-revised.ipynb":{"data":{"path":"lecture2-Loops-revised.ipynb","factory":"Notebook"}},"notebook:Lecture3-Exceptions-revised.ipynb":{"data":{"path":"Lecture3-Exceptions-revised.ipynb","factory":"Notebook"}},"notebook:Lecture4-Libraries-revised.ipynb":{"data":{"path":"Lecture4-Libraries-revised.ipynb","factory":"Notebook"}},"notebook:Lecture5-Unittest-revised.ipynb":{"data":{"path":"Lecture5-Unittest-revised.ipynb","factory":"Notebook"}},"notebook:lecture6-file io-revised.ipynb":{"data":{"path":"lecture6-file io-revised.ipynb","factory":"Notebook"}},"notebook:lecture7-regular expressions-revised.ipynb":{"data":{"path":"lecture7-regular expressions-revised.ipynb","factory":"Notebook"}},"notebook:lecture8-Object-oriented programming-revised.ipynb":{"data":{"path":"lecture8-Object-oriented programming-revised.ipynb","factory":"Notebook"}},"notebook:Lecture9-et-cetera-revised.ipynb":{"data":{"path":"Lecture9-et-cetera-revised.ipynb","factory":"Notebook"}}},"metadata":{"id":"default"}}